### PR TITLE
Fix wait editor

### LINKED ISSUE #21: Unstable open-editor
We notice that opening the editor in "wait" mode is not stable in:
- windows with vscode, notepad, notepad++

The issue happens when the editor is already opened, when it is closed it works (with tons of absolute path configured in order to run in windows).

The module used is [open](https://www.npmjs.com/package/open), preferred to `open-editor` because the last one doesn't have the `wait` option.

A snippet to try locally:
```
const { editMessage } = require('./lib/editor')

async function run () {
  const e = await editMessage('hello', 'hello.md')
  console.log(e)
}

run()
```

### PR DESCRIPTION
**Pull request by Eomm**
Closes #21 

Waiting to add these feature in the external module, we could manage by ourself the waiting child process.

Didn't check if `--wait` works for all the editors, but the commons ones it is ok:
- [vscode](https://code.visualstudio.com/docs/editor/command-line)
- [atom](https://help.github.com/en/articles/associating-text-editors-with-git)
- [sublime text](https://help.github.com/en/articles/associating-text-editors-with-git)

@mcollina For vim should I use `--remote-wait`?

We could manage the error in order to create anyway the github release and then suggest to edit it in the github website.

### CODE REVIEW

File: lib/editor.js [hunk 1]
```diff
@@ -2,22 +2,41 @@
...
+    const subProcess = spawn(editor.binary, editor.arguments, {
+      detached: true,
+      stdio: editor.isTerminalEditor ? 'inherit' : 'ignore',
+      shell: process.platform === 'win32'
+    })
+
+    subProcess.on('exit', (code) => {
+      if (code === 0) {
+        resolve()
+      }
```
Comment (mcollina) [inline lib/editor.js]: I think you should error if `code !== 0`.

File: test/command-publish.test.js [hunk 2]
```diff
@@ -274,8 +275,17 @@ test('publish a module minor editing the release message', async t => {
...
-          t.equals(tmpFile, fakeFile)
+        'open-editor': {
+          make: (tmpFile) => {
+            t.equals(tmpFile.pop(), fakeFile)
+          }
+        },
+        child_process: {
+          spawn: () => {
+            const e = new EventEmitter()
+            setImmediate(() => { e.emit('exit', 0) })
```
Comment (mcollina) [inline test/command-publish.test.js]: Would you mind adding a test where this fails with code != 0?

**Comment by Eomm** [comment]
In not sure about one thing: should we throw if the editing fails? Or we should catch it and display a warning that says "error editing, edit the message in the GH release"?

**Comment by mcollina** [comment]
I think we should throw.
